---
channels:
    1:
        active: true
        color: FF0000
        end: 12000.0
        label: Cy5
        max: 65535.0
        min: 0.0
        start: 2000.0
    2:
        active: true
        color: 00FF00
        end: 20000.0
        label: Cy3
        max: 65535.0
        min: 0.0
        start: 2000.0
    3:
        active: true
        color: 0000FF
        end: 15000.0
        label: TxR
        max: 65535.0
        min: 0.0
        start: 4000.0
    4:
        active: true
        color: FFFF00
        end: 4000.0
        label: Fam
        max: 65535.0
        min: 0.0
        start: 1500.0
    5:
        active: true
        color: FFFFFF
        end: 65535.0
        label: Phase
        max: 65535.0
        min: 0.0
        start: 0.0
greyscale: false
t: 1
version: 2
z: 1
